services:
  - type: web
    name: eclypse-backend
    env: bun
    buildCommand: bun install && bun run build
    startCommand: bun run start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: FRONTEND_URL
        sync: false 